name: mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  charts_flutter: ^0.12.0
  table_calendar: ^3.0.0
  get_storage: ^2.1.1
  http: ^0.13.5
  webview_flutter: ^4.8.0
  flutter: 
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  googleapis: ^9.0.0
  google_sign_in: ^5.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bg.png

